### PR TITLE
Flutter [Null Safety Migration]

### PR DESCRIPTION
**Pull request by abinvs-2019**

### CODE REVIEW

**Comment by abinvs-2019** [comment]
There is error while building the app from the kotlin side. That should also be updated.

**Comment by itzmeanjan** [comment]
I see too many file changes. It'll be little hard to review.

**Comment by abinvs-2019** [comment]
Yes there is too many changes because of migration to null safety. Also the app has issue form kotlin side. That should be taken care. Please do review and merge this request to move forward

**Comment by abinvs-2019** [comment]
> I see too many file changes. It'll be little hard to review.

@itzmeanjan  Is there anu update on the PR. I think there are no conflicts on the base branch. if there is no issues could you merge it. So we could fix other issues.

**Comment by itzmeanjan** [comment]
> > I see too many file changes. It'll be little hard to review.
> 
> @itzmeanjan Is there anu update on the PR. I think there are no conflicts on the base branch. if there is no issues could you merge it. So we could fix other issues.

Hi, I've not got the opportunity to review the changes yet. Also I'm not maintaining this project for sometime now, so it might be little hard for me to review and get it merged.

**Comment by abinvs-2019** [comment]
So should I close the PR.?

**Comment by itzmeanjan** [comment]
Hi, thanks for the PR, but I've to archive this repository.

**Pull request closed without merging**
